<?php
/**
 * GetMmsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Telstra_Messaging
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Telstra Messaging API
 *
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Telstra_Messaging;

use PHPUnit\Framework\TestCase;

/**
 * GetMmsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetMmsResponse
 * @package     Telstra_Messaging
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetMmsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetMmsResponse"
     */
    public function testGetMmsResponse()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "destination_address"
     */
    public function testPropertyDestinationAddress()
    {
    }

    /**
     * Test attribute "sender_address"
     */
    public function testPropertySenderAddress()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "message_id"
     */
    public function testPropertyMessageId()
    {
    }

    /**
     * Test attribute "api_msg_id"
     */
    public function testPropertyApiMsgId()
    {
    }

    /**
     * Test attribute "sent_timestamp"
     */
    public function testPropertySentTimestamp()
    {
    }

    /**
     * Test attribute "mms_content"
     */
    public function testPropertyMmsContent()
    {
    }
}
