<?php
/**
 * MessageSentResponseMmsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Telstra_Messaging
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Telstra Messaging API
 *
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Telstra_Messaging;

use PHPUnit\Framework\TestCase;

/**
 * MessageSentResponseMmsTest Class Doc Comment
 *
 * @category    Class
 * @description MessageSentResponseMms
 * @package     Telstra_Messaging
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MessageSentResponseMmsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MessageSentResponseMms"
     */
    public function testMessageSentResponseMms()
    {
    }

    /**
     * Test attribute "messages"
     */
    public function testPropertyMessages()
    {
    }

    /**
     * Test attribute "mms_media_kb"
     */
    public function testPropertyMmsMediaKb()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "message_type"
     */
    public function testPropertyMessageType()
    {
    }

    /**
     * Test attribute "number_segments"
     */
    public function testPropertyNumberSegments()
    {
    }
}
