<?php
/**
 * OutboundPollResponseInnerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Telstra_Messaging
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Telstra Messaging API
 *
 * The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages.
 *
 * OpenAPI spec version: 2.2.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Telstra_Messaging;

/**
 * OutboundPollResponseInnerTest Class Doc Comment
 *
 * @category    Class */
// * @description OutboundPollResponseInner
/**
 * @package     Telstra_Messaging
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OutboundPollResponseInnerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OutboundPollResponseInner"
     */
    public function testOutboundPollResponseInner()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "received_timestamp"
     */
    public function testPropertyReceivedTimestamp()
    {
    }

    /**
     * Test attribute "sent_timestamp"
     */
    public function testPropertySentTimestamp()
    {
    }

    /**
     * Test attribute "delivery_status"
     */
    public function testPropertyDeliveryStatus()
    {
    }
}
