<?php
/**
 * SendMmsRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Telstra_Messaging
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Telstra Messaging API
 *
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Telstra_Messaging;

use PHPUnit\Framework\TestCase;

/**
 * SendMmsRequestTest Class Doc Comment
 *
 * @category    Class
 * @description SendMmsRequest
 * @package     Telstra_Messaging
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SendMmsRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SendMmsRequest"
     */
    public function testSendMmsRequest()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "reply_request"
     */
    public function testPropertyReplyRequest()
    {
    }

    /**
     * Test attribute "notify_url"
     */
    public function testPropertyNotifyUrl()
    {
    }

    /**
     * Test attribute "mms_content"
     */
    public function testPropertyMmsContent()
    {
    }
}
