<?php
/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TelstraMessagingAPILib\Exceptions;

use TelstraMessagingAPILib\APIException;
use TelstraMessagingAPILib\APIHelper;

/**
 * @todo Write general description for this model
 */
class ErrorErrorError62ErrorException extends APIException
{
    /**
     * A short error code
     * @required
     * @var string $status public property
     */
    public $status;

    /**
     * Message describing the error.
     * @var string|null $message public property
     */
    public $message;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct($reason, $context)
    {
        parent::__construct($reason, $context);
    }

    /**
     * Unbox response into this exception class
     */
    public function unbox()
    {
        APIHelper::deserialize(self::getResponseBody(), $this, false, false);
    }
}
