<?php
/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TelstraMessagingAPILib\Exceptions;

use TelstraMessagingAPILib\APIException;
use TelstraMessagingAPILib\APIHelper;

/**
 * Returns error status code and message
 */
class ErrorErrorErrorErrorErrorException extends APIException
{
    /**
     * The status code.
     * @var integer|null $status public property
     */
    public $status;

    /**
     * Message describing the error.
     * @var string|null $message public property
     */
    public $message;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct($reason, $context)
    {
        parent::__construct($reason, $context);
    }

    /**
     * Unbox response into this exception class
     */
    public function unbox()
    {
        APIHelper::deserialize(self::getResponseBody(), $this, false, false);
    }
}
