<?php
/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TelstraMessagingAPILib\Models;

use JsonSerializable;

/**
 * Poll for incoming messages returning the latest. Only works if no url was specified when
 * provisioning a number.
 */
class InboundPollResponse implements JsonSerializable
{
    /**
     * The phone number (recipient) that the message was sent to(in
     * E.164 format).
     * @var string|null $destinationAddress public property
     */
    public $destinationAddress;

    /**
     * The phone number (sender) that the message was sent from (in
     * E.164 format).
     * @var string|null $senderAddress public property
     */
    public $senderAddress;

    /**
     * Text body of the message that was sent
     * @var string|null $message public property
     */
    public $message;

    /**
     * The date and time when the message was recieved by recipient.
     * @var string|null $sentTimestamp public property
     */
    public $sentTimestamp;

    /**
     * Optional message ID of the SMS you sent. Use this ID to viewthe message status or get responses.
     * @var string|null $messageId public property
     */
    public $messageId;

    /**
     * Message status from the server
     * @var string|null $status public property
     */
    public $status;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $destinationAddress Initialization value for $this->destinationAddress
     * @param string $senderAddress      Initialization value for $this->senderAddress
     * @param string $message            Initialization value for $this->message
     * @param string $sentTimestamp      Initialization value for $this->sentTimestamp
     * @param string $messageId          Initialization value for $this->messageId
     * @param string $status             Initialization value for $this->status
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->destinationAddress = func_get_arg(0);
            $this->senderAddress      = func_get_arg(1);
            $this->message            = func_get_arg(2);
            $this->sentTimestamp      = func_get_arg(3);
            $this->messageId          = func_get_arg(4);
            $this->status             = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['destinationAddress'] = $this->destinationAddress;
        $json['senderAddress']      = $this->senderAddress;
        $json['message']            = $this->message;
        $json['sentTimestamp']      = $this->sentTimestamp;
        $json['messageId']          = $this->messageId;
        $json['status']             = $this->status;

        return $json;
    }
}
