<?php
/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TelstraMessagingAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class MessageSentResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var Message[] $messages public property
     */
    public $messages;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $messageType public property
     */
    public $messageType;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $numberSegments public property
     */
    public $numberSegments;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $numberDestinations public property
     */
    public $numberDestinations;

    /**
     * Constructor to set initial or default values of member properties
     * @param array   $messages           Initialization value for $this->messages
     * @param string  $messageType        Initialization value for $this->messageType
     * @param integer $numberSegments     Initialization value for $this->numberSegments
     * @param integer $numberDestinations Initialization value for $this->numberDestinations
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->messages           = func_get_arg(0);
            $this->messageType        = func_get_arg(1);
            $this->numberSegments     = func_get_arg(2);
            $this->numberDestinations = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['messages']           = $this->messages;
        $json['messageType']        = $this->messageType;
        $json['numberSegments']     = $this->numberSegments;
        $json['numberDestinations'] = $this->numberDestinations;

        return $json;
    }
}
