<?php
/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TelstraMessagingAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class MessageTypeEnum
{
    /**
     * TODO: Write general description for this element
     */
    const SMS = "SMS";

    /**
     * TODO: Write general description for this element
     */
    const MMS = "MMS";

    /**
     * TODO: Write general description for this element
     */
    const RCS = "RCS";
}
