<?php
/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TelstraMessagingAPILib\Models;

/**
 * OAuth 2 scopes supported by the API
 */
class OAuthScopeEnum
{
    /**
     * NSMS
     */
    const NSMS = "NSMS";
}
