<?php
/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TelstraMessagingAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class OutboundPollResponse implements JsonSerializable
{
    /**
     * The phone number (recipient) the message was sent to (in E.164
     * format).
     * @var string|null $to public property
     */
    public $to;

    /**
     * The date and time when the message was recieved by recipient.
     * @var string|null $receivedTimestamp public property
     */
    public $receivedTimestamp;

    /**
     * The date and time when the message was sent.
     * @var string|null $sentTimestamp public property
     */
    public $sentTimestamp;

    /**
     * @todo Write general description for this property
     * @var string|null $deliveryStatus public property
     */
    public $deliveryStatus;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $to                Initialization value for $this->to
     * @param string $receivedTimestamp Initialization value for $this->receivedTimestamp
     * @param string $sentTimestamp     Initialization value for $this->sentTimestamp
     * @param string $deliveryStatus    Initialization value for $this->deliveryStatus
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->to                = func_get_arg(0);
            $this->receivedTimestamp = func_get_arg(1);
            $this->sentTimestamp     = func_get_arg(2);
            $this->deliveryStatus    = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['to']                = $this->to;
        $json['receivedTimestamp'] = $this->receivedTimestamp;
        $json['sentTimestamp']     = $this->sentTimestamp;
        $json['deliveryStatus']    = $this->deliveryStatus;

        return $json;
    }
}
