<?php
/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TelstraMessagingAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ProvisionNumberRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var integer|null $activeDays public property
     */
    public $activeDays;

    /**
     * @todo Write general description for this property
     * @var string|null $notifyURL public property
     */
    public $notifyURL;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $activeDays Initialization value for $this->activeDays
     * @param string  $notifyURL  Initialization value for $this->notifyURL
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->activeDays = func_get_arg(0);
            $this->notifyURL  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['activeDays'] = $this->activeDays;
        $json['notifyURL']  = $this->notifyURL;

        return $json;
    }
}
