<?php
/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TelstraMessagingAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class StatusEnum
{
    /**
     * TODO: Write general description for this element
     */
    const PEND = "PEND";

    /**
     * TODO: Write general description for this element
     */
    const SENT = "SENT";

    /**
     * TODO: Write general description for this element
     */
    const DELIVRD = "DELIVRD";

    /**
     * TODO: Write general description for this element
     */
    const EXPIRED = "EXPIRED";

    /**
     * TODO: Write general description for this element
     */
    const DELETED = "DELETED";

    /**
     * TODO: Write general description for this element
     */
    const UNDVBL = "UNDVBL";

    /**
     * TODO: Write general description for this element
     */
    const REJECTED = "REJECTED";

    /**
     * TODO: Write general description for this element
     */
    const READ = "READ";
}
