<?php
/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TelstraMessagingAPILib;

/**
 * Baseurl aliases
 */
class Servers
{
    /**
     * TODO: Write general description for this element
     */
    const DEFAULT_ = "default";

    /**
     * TODO: Write general description for this element
     */
    const ACCESS_TOKEN_SERVER = "access token server";
}
