<?php
/**
 * MessagingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Telstra_Messaging
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Telstra Messaging API
 *
 * The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages.
 *
 * OpenAPI spec version: 2.2.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Telstra_Messaging;

use \Telstra_Messaging\Configuration;
use \Telstra_Messaging\ApiException;
use \Telstra_Messaging\ObjectSerializer;

/**
 * MessagingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Telstra_Messaging
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessagingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getMMSStatus
     *
     * Get MMS Status.
     *
     */
    public function testGetMMSStatus()
    {
    }

    /**
     * Test case for getSMSStatus
     *
     * Get SMS Status.
     *
     */
    public function testGetSMSStatus()
    {
    }

    /**
     * Test case for retrieveSMSResponses
     *
     * Retrieve SMS Responses.
     *
     */
    public function testRetrieveSMSResponses()
    {
    }

    /**
     * Test case for sendMMS
     *
     * Send MMS.
     *
     */
    public function testSendMMS()
    {
    }

    /**
     * Test case for sendSMS
     *
     * Send SMS.
     *
     */
    public function testSendSMS()
    {
    }
}
