<?php
/**
 * MessagingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Telstra_Messaging
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Telstra Messaging API
 *
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Telstra_Messaging;

use \Telstra_Messaging\Configuration;
use \Telstra_Messaging\ApiException;
use \Telstra_Messaging\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MessagingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Telstra_Messaging
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MessagingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getMMSStatus
     *
     * Get MMS Status.
     *
     */
    public function testGetMMSStatus()
    {
    }

    /**
     * Test case for getSMSStatus
     *
     * Get SMS Status.
     *
     */
    public function testGetSMSStatus()
    {
    }

    /**
     * Test case for mMSHealthCheck
     *
     * MMS Health Check.
     *
     */
    public function testMMSHealthCheck()
    {
    }

    /**
     * Test case for retrieveMMSReplies
     *
     * Retrieve MMS Replies.
     *
     */
    public function testRetrieveMMSReplies()
    {
    }

    /**
     * Test case for retrieveSMSReplies
     *
     * Retrieve SMS Replies.
     *
     */
    public function testRetrieveSMSReplies()
    {
    }

    /**
     * Test case for sMSHealthCheck
     *
     * SMS Health Check.
     *
     */
    public function testSMSHealthCheck()
    {
    }

    /**
     * Test case for sMSMulti
     *
     * Send Multiple SMS.
     *
     */
    public function testSMSMulti()
    {
    }

    /**
     * Test case for sendMMS
     *
     * Send MMS.
     *
     */
    public function testSendMMS()
    {
    }

    /**
     * Test case for sendSMS
     *
     * Send SMS.
     *
     */
    public function testSendSMS()
    {
    }
}
